# Dockerfile_training

# Use a base image with Python installed
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY ml_pipeline/requirements.txt ./

# Install necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire Data directory into the container
COPY ml_pipeline/Data /app/Data

# Copy the rest of application code into the container
COPY . .


ENV MODEL_PATH=/app/models/xgboost_model.pkl
# Command to run your training script
CMD ["python", "monitoring.py"]
