

image: python:3.12-slim



variables:
  PYTHONUNBUFFERED: 1

stages:
  - test
  - build
  - deploy

before_script:
  - pip install --no-cache-dir -r requirements.txt

test:
  stage: test
  script:
    - pytest tests/test_prediction.py

build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker build -t myapp:latest .

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker-compose up -d
  only:
    - master  # Deploy only when changes are pushed to the master branch
