# Using Python 3.10 base image
FROM python:3.10

# Setting the working directory inside the container
WORKDIR /app

# Copy the entire ml_pipeline directory into the container
COPY . /app

# Installing necessary dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Setting environment variables for paths used in the container
ENV MODEL_PATH=/app/models/xgboost_model.pkl

# Starting the FastAPI application for inference
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]