version: '3'
services:
  training:
    build:
      context: .
      dockerfile: Dockerfile_training
    volumes:
      - ./ml_pipeline:/app/ml_pipeline  # Sharing model files and data
    environment:
      - MODEL_PATH=/app/ml_pipeline/models/xgboost_model.pkl
      - DATA_PATH=/app/ml_pipeline/Data/datatraining.txt
    restart: always  #  running to monitor for new data

  inference:
    build:
      context: .
      dockerfile: Dockerfile_inference
    volumes:
      - ./ml_pipeline:/app/ml_pipeline  # Sharing model files
    ports:
      - "8000:8000"  # Exposing FastAPI app on port 8000
    environment:
      - MODEL_PATH=/app/ml_pipeline/models/xgboost_model.pkl
    restart: always  # Keeping it running to serve predictions
