# Using Python 3.10 base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY --chown=root:root requirements.txt /app/requirements.txt

# Install necessary dependencies
RUN pip install --upgrade pip && pip install -r /app/requirements.txt

# Ensure the Data directory exists inside the container
RUN mkdir -p /app/ml_pipeline/Data

# Copy the rest of the application code to the container
COPY . /app

# Set environment variables
ENV MODEL_PATH=/app/models/xgboost_model.pkl
ENV DATA_PATH=/app/ml_pipeline/Data/datatraining.txt

# Command to run the training process
CMD ["python", "-m", "monitoring"]
