

# Useing Python 3.12 base image
FROM python:3.12-slim

# Setting the working directory inside the container
WORKDIR /app

# Copy all your local project files to the container
COPY . /app

# Installing necessary dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Setting environment variables for paths used in the container
ENV MODEL_PATH=/app/ml_pipeline/models/xgboost_model.pkl
ENV DATA_PATH=/app/ml_pipeline/Data/datatraining.txt

# The entrypoint command for the container, this runs monitoring.py to monitor the directory
CMD ["python", "-m", "ml_pipeline.monitoring"]
